


      # .github/workflows/full_deploy.yml
      name: Full Deploy

      on:
        push:
          branches:
            - main  # Trigger on push to the main branch

      jobs:
        deploy:
          runs-on: ubuntu-latest

          env:
            VERSION_FILE: VERSION

          steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.23.2'  # Specify the Go version

            - name: Azure Login
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Set environment variables
              run: |
                echo "APP_NAME=zkillanalytics" >> $GITHUB_ENV
                echo "GROUP_NAME=flygd" >> $GITHUB_ENV
                echo "AZURE_CONTAINER_REGISTRY=${GROUP_NAME}.azurecr.io" >> $GITHUB_ENV

            - name: Increment version
              id: version
              run: |
                VERSION=$(cat $VERSION_FILE)
                NEW_VERSION=$(echo $VERSION | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}')
                echo "${NEW_VERSION}" > $VERSION_FILE
                echo "VERSION=${NEW_VERSION}" >> $GITHUB_ENV
                echo "New version: $NEW_VERSION"
              shell: bash

            - name: Build Go application
              run: go build -o zkill

            - name: Push image to Azure Container Registry
              run: |
                az acr build --image "${GROUP_NAME}/${APP_NAME}:${VERSION}" \
                  --registry "${GROUP_NAME}" \
                  --build-arg VERSION="${VERSION}" .

            - name: Update Azure Container App
              run: |
                az containerapp update -n $APP_NAME -g $GROUP_NAME \
                  --image "${AZURE_CONTAINER_REGISTRY}/${GROUP_NAME}/${APP_NAME}:${VERSION}"

            - name: Restart Azure Container App Revision
              run: |
                REVISION=$(az containerapp revision list --name $APP_NAME --resource-group $GROUP_NAME --query "[].name" -o tsv)
                az containerapp revision restart -n $APP_NAME -g $GROUP_NAME --revision $REVISION
